#!/bin/bash

CONTAINER_REGISTRY="kakalin"
CONTAINER_REPOSITORY="xilinx"
CONTAINER_TAG="dnndk3.1-cuda10.0-tf1.2"

docker build --platform linux/x86_64 --rm -t $CONTAINER_REGISTRY/$CONTAINER_REPOSITORY:$CONTAINER_TAG .
docker push $CONTAINER_REGISTRY/$CONTAINER_REPOSITORY:$CONTAINER_TAG
