#!/bin/bash

CONTAINER_REGISTRY="kakalin"
CONTAINER_REPOSITORY="kimage"
CONTAINER_TAG="cuda11.3-torch1.12.0-devel"

docker build --rm -t $CONTAINER_REGISTRY/$CONTAINER_REPOSITORY:$CONTAINER_TAG .
docker push $CONTAINER_REGISTRY/$CONTAINER_REPOSITORY:$CONTAINER_TAG
